# Generated by Django 5.0 on 2024-06-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0002_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otptoken',
            old_name='otp_expired_at',
            new_name='otp_expires_at',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='184780', max_length=6),
        ),
    ]
