# Generated by Django 5.0 on 2024-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0007_category_alter_otptoken_otp_code_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='07ed24', max_length=6),
        ),
    ]
