# Generated by Django 5.0 on 2024-06-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0008_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frameworks',
            field=models.CharField(choices=[(1, 'Django'), (2, 'React'), (3, 'Express'), (4, 'Spring Boot'), (5, 'Flask'), (6, 'FastAPI'), (7, 'Django REST framework'), (8, 'Vue.js'), (9, 'Angular'), (10, 'Laravel')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='7cc387', max_length=6),
        ),
    ]
