# Generated by Django 5.0 on 2024-06-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0010_product_programming_language_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='3419a9', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='programming_language',
            field=models.CharField(choices=[(1, 'Python'), (2, 'JavaScript'), (3, 'Java'), (4, 'C#'), (5, 'Ruby'), (6, 'PHP'), (7, 'Go'), (8, 'Swift'), (9, 'Kotlin'), (10, 'TypeScript')], max_length=100),
        ),
    ]
