# Generated by Django 5.0 on 2024-06-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0013_alter_otptoken_otp_code_alter_product_frameworks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='64783e', max_length=6),
        ),
    ]
