# Generated by Django 5.0 on 2024-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0015_product_course_content_product_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='screenshot2',
            field=models.ImageField(null=True, upload_to='uploads/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='screenshot3',
            field=models.ImageField(null=True, upload_to='uploads/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='screenshot4',
            field=models.ImageField(null=True, upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='6437a4', max_length=6),
        ),
    ]
