# Generated by Django 5.0 on 2024-06-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0016_product_screenshot2_product_screenshot3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='380de9', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='screenshot1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product/'),
        ),
    ]
