# Generated by Django 5.0 on 2024-06-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0017_alter_otptoken_otp_code_alter_product_screenshot1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='89f244', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='screenshot1',
            field=models.ImageField(blank=True, default=1, upload_to='uploads/product/'),
            preserve_default=False,
        ),
    ]
