# Generated by Django 5.0 on 2024-06-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0018_alter_otptoken_otp_code_alter_product_screenshot1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='dee2e2', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='screenshot1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screenshot2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screenshot3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screenshot4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product/'),
        ),
    ]
